site_name: NPU2World
site_author: 'NPU2World Group'
copyright: '&copy; 2023 npu2world'
theme:
  name: material
  palette:
  - scheme: default
    primary: blue
    accent: amber
  features:
    - content.action.edit
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - toc.follow
    - search.highlight

nav:
  - NPU CS/EE 飞跃手册: 
    - HOME: index.md
    - DataPoints:
      - 2017级-Econ-Gearing(MDS @USYD): DataPoints/2017级-Econ-Gearing.md
      - 2019级-HC-袁浩程(CS PhD @ The University of Edinburgh): DataPoints/2019级-HC-袁浩程.md
      - 2019级-HC-倪航(AI PhD @ HKUSTgz): DataPoints/2019级-HC-倪航.md
      - 2019级-电信-柳煜翔(EE Msc @NUS): DataPoints/2019级-电信-柳煜翔.md 
      - 2019级-航空-余卓远(ME MEng @NUS): DataPoints/2019级-航空-余卓远.md
      - 2019级-计科-江嘉熙(CS PHD @CUHK/CSE): DataPoints/2019级-计科-江嘉熙.md
      - 2019级-民航-李官翰(Msc @IC): DataPoints/2019级-民航-李官翰.md
      - 2019级-民航-李官翰(MPhil @Cambridge): DataPoints/2019级-民航-李官翰(二硕).md
      - 2020级-SE-游俊(CS PhD @CityU): DataPoints/2020级-软件-游俊.md
      - 2020级-Math-刘一恒(MATH@ALGANT): DataPoints/2020级-数学-刘一恒.md
      - 2020级-计科-蒋晓天(ES MSc@KTH): DataPoints/2020级-计科-蒋晓天.md
      - 2020级-计科-Eliza(MSc@UA): DataPoints/2020级-计科-Eliza.md
      - 2020级-航发-权奕迪(MSc@KTH): DataPoints/2020级-航发-权奕迪.md
    - 学校合作交流项目: projectComment.md
    - 暑研信息汇总: summerProgramm.md
    - 标化经验分享: 
      - GRE经验-锅锅锅: 标化经验分享/关于GRE-锅锅锅.md
      - GRE备考-Anan: 标化经验分享/GRE备考-Anan.md
      - 雅思备考-Anan: 标化经验分享/雅思备考-Anan.md
    - 暑研实习经验分享:
      - 14-闫奕岐-Mitacs: 其他经验/14-闫奕岐-Mitacs.md
      - 20-刘子骞-阿尔伯塔大学csc暑研: 其他经验/20-刘子骞-阿尔伯塔大学csc暑研.md
    - 校内材料开具教程:
      - 如何申请中英文成绩单-锅锅锅: 其他经验/如何申请中英文成绩单-锅锅锅.md
    - 海外毕设分享: 其他经验/20-王申-本科毕设分享.md
    - 实用网站: instruction.md
    - Intern/Research合作信息: researchInfo.md
    

repo_name: NPU2World
repo_url: https://github.com/NPU2World/NPU2World
remote_branch: gh-pages