site_name: NPU2World
theme:
  name: null
  custom_dir: 'mkdocs_docskimmer'
  include_search_page: true
  search_index_only: false
  static_templates:
  - 404.html

plugins: ['search']

# add theme version number here
extra:
    version: 0.4.0