site_name: NPU2World
site_author: 'NPU2World Group'
copyright: '&copy; 2023 npu2world'
theme:
  name: material
  palette:
  - scheme: default
    primary: blue
    accent: amber
  features:
    - content.action.edit
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - toc.follow
    - search.highlight

nav:
  - NPU CS/EE 飞跃手册: 
    - HOME: index.md
    - DataPoints:
      - 2017级-Econ-Gearing(MDS @USYD): DataPoints/2017级-Econ-Gearing.md
      - 2019级-HC-袁浩程(CS PhD @ The University of Edinburgh): DataPoints/2019级-HC-袁浩程.md
      - 2019级-HC-倪航(AI PhD @ HKUSTgz): DataPoints/2019级-HC-倪航.md
      - 2019级-电信-柳煜翔(EE Msc @NUS): DataPoints/2019级-电信-柳煜翔.md 
    - 学校合作交流项目: projectComment.md
    - 暑研信息汇总: summerProgramm.md
    - 标化经验分享: 
      - IELTS:
        - 19-CS-Anan: 标化经验分享/IELTS/19-CS-Anan.md
      - GRE:
        - 19-CS-Anan: 标化经验分享/GRE/19-CS-Anan.md
    - 暑研实习经验分享:
      - 14-闫奕岐-Mitacs: 其他经验/14-闫奕岐-Mitacs.md
      - 20-刘子骞-阿尔伯塔大学csc暑研: 其他经验/20-刘子骞-阿尔伯塔大学csc暑研.md
    - 实用网站: instruction.md
    

repo_name: NPU2World
repo_url: https://github.com/NPU2World/NPU2World
remote_branch: gh-pages